### PR TITLE
docs: developer bounties

### PR DESCRIPTION
**Pull request by MicBun**
resolves: https://github.com/truf-network/truf-network/issues/16
resolves: https://github.com/truf-network/truf-network/issues/19

add new section for bounty here
image

### CODE REVIEW

**Comment by MicBun** [comment]
@zolotokrylin @markholdex, could you check my writings?

**Comment by zolotokrylin** [comment]
Well done!

**Review by georgeciubotaru — COMMENTED** [review]
testing comment

**Comment by georgeciubotaru** [comment]
@MicBun For the future, please avoid `force-push`

**Pull request merged**
